site_name: "Dr. Byrd's Eye"
site_url: https://brookbyrd.github.io/

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.indexes
    - navigation.footer

plugins:
  - search
