site_name: "Dr. Byrd's Eye"
site_url: https://brookbyrd.github.io/

theme:
  name: material
  palette:
    scheme: slate

plugins:
  - search

nav:
  - Home: index.md

  - 01. Therapy Physics Basics: 01. Therapy Physics Basics/index.md

  - 1.1 Basic Interactions:
      - Overview: 01. Therapy Physics Basics/1.1 Basic Interactions/index.md

  - 1.2 Cavity Theory:
      - Overview: 01. Therapy Physics Basics/1.2 Cavity Theory/index.md

  - 1.3 PDDs:
      - Overview: 01. Therapy Physics Basics/1.3 PDDs/index.md